const listings=[
 {id:1,title:'كنبة زاوية مودرن بحالة ممتازة',place:'الرياض · النرجس',price:'1,850 ر.س',time:'منذ ساعتين',icon:'🛋️',tone:'t1',cat:'المنزل والمفروشات'},
 {id:2,title:'آيفون 15 برو 256GB',place:'جدة · الروضة',price:'3,950 ر.س',time:'منذ 3 ساعات',icon:'📱',tone:'t2',cat:'الإلكترونيات'},
 {id:3,title:'شقة عائلية للإيجار',place:'الخبر · العليا',price:'42,000 ر.س / سنة',time:'أمس',icon:'🏢',tone:'t3',cat:'العقارات'},
 {id:4,title:'تويوتا كامري 2022',place:'الرياض · الياسمين',price:'92,000 ر.س',time:'أمس',icon:'🚙',tone:'t4',cat:'السيارات'},
 {id:5,title:'طاولة طعام خشب طبيعي',place:'الدمام · الفيصلية',price:'780 ر.س',time:'منذ يومين',icon:'🪑',tone:'t1',cat:'المنزل والمفروشات'},
 {id:6,title:'كاميرا سوني احترافية',place:'مكة · العزيزية',price:'2,400 ر.س',time:'منذ 3 أيام',icon:'📷',tone:'t2',cat:'الإلكترونيات'}
];
const cats=[['🛋️','المنزل والمفروشات'],['📱','الإلكترونيات'],['🏠','العقارات'],['🚗','السيارات'],['✨','أخرى'],['💄','الموضة والجمال'],['🛠️','الخدمات'],['💼','الوظائف']];
const app=document.querySelector('#app');let favorites=JSON.parse(localStorage.getItem('matlabFav')||'[]');
function go(route){location.hash=route;window.scrollTo({top:0,behavior:'smooth'})}function icon(name){return {home:'⌂',search:'⌕',heart:'♡',chat:'◌',user:'◉'}[name]||''}
function logo(){return `<img src="matlab-logo.jpg" alt="مطلب - كل ما تحتاجه في مكان واحد">`}function header(){return `<header class="top shell"><div class="brand" onclick="go('/')">${logo()}</div><nav class="nav"><a onclick="go('/')">الرئيسية</a><a onclick="go('/search')">التصنيفات</a><a onclick="go('/messages')">الرسائل</a><a onclick="go('/favorites')">المفضلة</a></nav><div class="header-actions"><span class="action-link" onclick="go('/messages')">💬 الرسائل</span><button class="login" onclick="go('/login')">تسجيل الدخول</button><button class="post-btn" onclick="go('/post')">＋ إضافة إعلان</button></div></header>`}
function mobile(route){return `<nav class="mobile-nav"><button class="${route==='/'?'active':''}" onclick="go('/')">⌂<br>الرئيسية</button><button class="${route==='/search'?'active':''}" onclick="go('/search')">⌕<br>بحث</button><button onclick="go('/post')">＋<br>أضف إعلان</button><button class="${route==='/favorites'?'active':''}" onclick="go('/favorites')">♡<br>المفضلة</button><button class="${route==='/account'?'active':''}" onclick="go('/account')">◉<br>حسابي</button></nav>`}
function card(x){let saved=favorites.includes(x.id);return `<article class="card" onclick="go('/listing/${x.id}')"><div class="thumb ${x.tone}"><span class="tag">مميز</span><button class="heart" onclick="event.stopPropagation();toggleFav(${x.id})">${saved?'♥':'♡'}</button>${x.icon}</div><div class="card-info"><div class="title">${x.title}</div><div class="meta"><span>📍 ${x.place}</span><span>${x.time}</span></div><div class="price">${x.price}</div></div></article>`}
function searchBar(){return `<div class="search-wrap"><input id="quickSearch" placeholder="ما الذي تبحث عنه؟" onkeydown="if(event.key==='Enter')go('/search?q='+encodeURIComponent(this.value))"><button class="filter" onclick="go('/search')">⚙ الفلاتر</button><button class="search" onclick="go('/search?q='+encodeURIComponent(document.querySelector('#quickSearch').value))">بحث</button></div>`}
function home(){return `<main><section class="hero"><div class="sun"></div><div class="arches"></div><div class="hero-copy"><div class="eyebrow">سوقك المحلي، على بُعد خطوة</div><h1>مطلب</h1><p>أبسط طريقة لبيع وشراء كل ما تحتاجه</p></div></section>${searchBar()}<div class="shell"><section class="section"><div class="section-head"><h2>تصفح حسب القسم</h2><span class="more" onclick="go('/search')">عرض الكل ←</span></div><div class="categories">${cats.map(c=>`<div class="category" onclick="go('/search?cat='+encodeURIComponent(c[1]))"><div class="icon">${c[0]}</div><span>${c[1]}</span></div>`).join('')}</div></section><section class="section"><div class="section-head"><h2>إعلانات مميزة</h2><span class="more" onclick="go('/search')">عرض المزيد ←</span></div><div class="products">${listings.slice(0,4).map(card).join('')}</div></section><section class="section"><div class="features"><div class="feature"><i>✓</i><span><b>تجربة آمنة</b><small>تواصل بثقة واطمئنان</small></span></div><div class="feature"><i>♧</i><span><b>دعم متواصل</b><small>نحن هنا لمساعدتك</small></span></div><div class="feature"><i>⚡</i><span><b>إعلانات سريعة</b><small>انشر إعلانك خلال دقائق</small></span></div><div class="feature"><i>♟</i><span><b>مجتمع مستخدمين</b><small>الآلاف بالقرب منك</small></span></div></div></section></div></main>`}
function listing(id){let x=listings.find(a=>a.id===+id)||listings[0];return `<main class="shell page"><div class="crumb">الرئيسية / ${x.cat} / ${x.title}</div><div class="detail-grid"><div><div class="detail-photo ${x.tone}">${x.icon}</div><section class="panel" style="margin-top:18px"><h2>وصف الإعلان</h2><p style="line-height:2;color:var(--muted)">إعلان تجريبي قابل للتعديل. المنتج بحالة ممتازة ومستخدم بعناية، ويمكن المعاينة والاتفاق مع البائع عبر الرسائل داخل منصة مطلب.</p></section></div><aside class="panel"><div class="meta"><span>${x.cat}</span><span>${x.time}</span></div><h1>${x.title}</h1><div class="price" style="font-size:25px">${x.price}</div><div class="details"><div>الموقع<b>📍 ${x.place}</b></div><div>الحالة<b>مستعمل بحالة ممتازة</b></div></div><div class="contact"><button class="primary" onclick="go('/messages')">💬 مراسلة البائع</button><button class="outline" onclick="toggleFav(${x.id})">${favorites.includes(x.id)?'♥ محفوظ':'♡ حفظ الإعلان'}</button></div><p style="text-align:center;color:var(--muted);font-size:11px;margin-top:20px">لا تشارك بياناتك الحساسة خارج المنصة.</p></aside></div></main>`}
function searchPage(){let p=new URLSearchParams(location.hash.split('?')[1]||'');let q=p.get('q')||'',cat=p.get('cat')||'';let shown=listings.filter(x=>!q||x.title.includes(q)||x.cat.includes(q));if(cat)shown=shown.filter(x=>x.cat===cat);return `<main class="shell page"><div class="crumb">الرئيسية / نتائج البحث</div><div class="search-page"><aside class="panel filters"><h2>تصفية النتائج</h2><label>القسم</label><select onchange="go('/search?cat='+encodeURIComponent(this.value))"><option value="">كل الأقسام</option>${cats.map(c=>`<option ${cat===c[1]?'selected':''}>${c[1]}</option>`).join('')}</select><label>المدينة</label><select><option>كل المدن</option><option>الرياض</option><option>جدة</option><option>الدمام</option></select><label>السعر</label><input placeholder="مثال: 1000" type="number"><label>ترتيب حسب</label><select><option>الأحدث</option><option>السعر: الأقل أولاً</option><option>السعر: الأعلى أولاً</option></select></aside><section><div class="section-head"><h2>${q?`نتائج البحث عن «${q}»`:'كل الإعلانات'}</h2><span style="color:var(--muted)">${shown.length} إعلان</span></div><div class="results">${shown.map(card).join('')||'<div class="panel">لا توجد نتائج مطابقة.</div>'}</div></section></div></main>`}
function post(){return `<main class="shell page form"><div class="crumb">الرئيسية / إضافة إعلان</div><section class="panel"><h1>أضف إعلانك</h1><p style="color:var(--muted)">أدخل التفاصيل الأساسية، ثم انشر إعلانك خلال دقائق.</p><label>عنوان الإعلان</label><input id="postTitle" placeholder="مثال: جهاز آيفون 15 بحالة ممتازة"><label>القسم</label><select><option>المنزل والمفروشات</option><option>الإلكترونيات</option><option>العقارات</option><option>السيارات</option><option>الخدمات</option></select><label>المدينة</label><select><option>الرياض</option><option>جدة</option><option>الدمام</option><option>مكة</option></select><label>السعر (ر.س)</label><input type="number" placeholder="0"><label>وصف الإعلان</label><textarea placeholder="اكتب وصفًا واضحًا ومختصرًا..."></textarea><button class="primary" onclick="publish()">نشر الإعلان</button></section></main>`}
function login(){return `<main class="shell page auth"><section class="panel"><div class="brand" style="justify-content:center">${logo()}</div><h1>أهلاً بعودتك</h1><p>سجّل دخولك للوصول إلى رسائلك وإعلاناتك المفضلة.</p><div class="stack"><input placeholder="رقم الجوال" type="tel"><button class="primary" onclick="toast('تم إرسال رمز التحقق إلى جوالك')">إرسال رمز التحقق</button><button class="outline" style="padding:12px" onclick="go('/account')">الدخول كحساب تجريبي</button></div></section></main>`}
function favoritesPage(){let items=listings.filter(x=>favorites.includes(x.id));return `<main class="shell page"><div class="section-head"><h1>إعلاناتي المفضلة</h1></div>${items.length?`<div class="products">${items.map(card).join('')}</div>`:`<section class="panel empty"><div class="big">♡</div><h2>لا توجد إعلانات محفوظة</h2><p style="color:var(--muted)">اضغط على رمز القلب في أي إعلان ليظهر هنا.</p><button class="primary" onclick="go('/search')">تصفح الإعلانات</button></section>`}</main>`}
function messages(){return `<main class="shell page" style="max-width:850px"><h1>الرسائل</h1><section class="panel"><div class="tabs"><button class="tab active">الكل</button><button class="tab">غير مقروءة</button></div>${[['🧔','أحمد السالم','مهتم بالسيارة، هل ما زالت متاحة؟','منذ 10 دقائق'],['👩','سارة محمد','مرحباً، هل يوجد توصيل؟','أمس'],['🧑','مؤسسة البيت الحديث','شكراً لتواصلك معنا.','منذ 3 أيام']].map(m=>`<div class="message" onclick="toast('هذه محادثة تجريبية')"><div class="avatar">${m[0]}</div><div style="flex:1"><b>${m[1]}</b><div style="color:var(--muted);margin-top:4px">${m[2]}</div></div><small>${m[3]}</small></div>`).join('')}</section></main>`}
function account(){return `<main class="shell page profile"><aside class="panel profile-side"><div class="avatar">👤</div><h2>حساب تجريبي</h2><p style="color:var(--muted);font-size:12px">عضو في مطلب</p><div class="profile-menu"><button onclick="toast('لا توجد إعلانات منشورة بعد')">إعلاناتي</button><button onclick="go('/favorites')">المفضلة</button><button onclick="go('/messages')">الرسائل</button><button onclick="go('/login')">تسجيل الخروج</button></div></aside><section class="panel"><h1>إعدادات الحساب</h1><div class="form"><label>الاسم</label><input value="حساب تجريبي"><label>رقم الجوال</label><input value="05XXXXXXXX"><label>المدينة</label><select><option>الرياض</option><option>جدة</option><option>الدمام</option></select><button class="primary" onclick="toast('تم حفظ التعديلات بنجاح')">حفظ التعديلات</button></div></section></main>`}
function toast(text){let e=document.createElement('div');e.className='toast';e.textContent=text;document.body.append(e);setTimeout(()=>e.remove(),2600)}function toggleFav(id){favorites=favorites.includes(id)?favorites.filter(x=>x!==id):[...favorites,id];localStorage.setItem('matlabFav',JSON.stringify(favorites));toast(favorites.includes(id)?'تمت إضافة الإعلان إلى المفضلة':'تمت إزالة الإعلان من المفضلة');render() }function publish(){let title=document.querySelector('#postTitle').value.trim();if(!title)return toast('أضف عنواناً للإعلان أولاً');toast('تم نشر إعلانك التجريبي بنجاح!');setTimeout(()=>go('/'),700)}
function render(){let path=location.hash.slice(1)||'/';let view=path.startsWith('/listing/')?listing(path.split('/')[2]):path.startsWith('/search')?searchPage():({'/':home,'/post':post,'/login':login,'/favorites':favoritesPage,'/messages':messages,'/account':account}[path]||home)();app.innerHTML=header()+view+mobile(path.startsWith('/listing')?'/':path.split('?')[0])}window.addEventListener('hashchange',render);render();
